name: Build and publish

on:
  push:
  workflow_dispatch:

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      NO_LIMIT: nolimit
      R_USER: ${{secrets.R_USER}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: pip
      run: pip install -r requirements.txt
    - name: build
      run: ./build.sh
    - name: Deploy Graph
      run: ./update_graph.sh
