name: enricht listfackel
on:
  workflow_dispatch
jobs:
  build_pages:
    name: enrich listfackel-index with data from fa-data/data/indices/fackelTexts_cascaded.xml
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: pip
      run:
        pip install -r requirements.txt
    - name: enrich
      run: python scripts/enrich_fackel_bibls.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: updated indices/listfackel.xml with data from https://raw.githubusercontent.com/semantic-kraus/fa-data/main/data/indices/fackelTexts_cascaded.xml